use_frameworks!

platform :ios, '8.0'

target 'MJAdaptScreenHelp_Example' do
  pod 'MJAdaptScreenHelp', :path => '../'

  target 'MJAdaptScreenHelp_Tests' do
    inherit! :search_paths

    
  end
end
